name = "BiobakeryUtils"
uuid = "fa5322f5-bd84-5069-834a-abf3230fb8f8"
keywords = ["microbiology", "microbiome", "biology", "metagenomics"]
license = "MIT"
desc = "Convenience functions for working with the bioBakery"
authors = ["kescobo <kevbonham@gmail.com>", "annelle-abatoni <aa1@wellesley.edu>", "anikaluo <al8@wellesley.edu>", "Vanja Klepac-Ceraj <vklepacc@wellesley.edu>"]
version = "0.6.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Microbiome = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CSV = "0.8, 0.9, 0.10"
Microbiome = "0.9"
ReTest = "0.3"
Reexport = "0.2, 1"
Tables = "1.2.1"
julia = "1.6"
