name = "BiobakeryUtils"
uuid = "fa5322f5-bd84-5069-834a-abf3230fb8f8"
keywords = ["microbiology", "microbiome", "biology", "metagenomics"]
license = "MIT"
desc = "Convenience functions for working with the bioBakery"
authors = ["kescobo <kevbonham@gmail.com>", "annelle-abatoni <aa1@wellesley.edu>", "anikaluo <al8@wellesley.edu>", "Vanja Klepac-Ceraj <vklepacc@wellesley.edu>"]
version = "0.5.0-dev"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
<<<<<<< HEAD
<<<<<<< HEAD
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
=======
>>>>>>> 3381d39ddcdbfaa2bd78728383e785d395189e5a
=======
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
>>>>>>> 613284926d1a5a9b23a0fd2e3a423b189097cb61
Microbiome = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CSV = "0.8, 0.9"
Microbiome = "0.7, 0.8"
julia = "1.1"
